config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :learn_more do
    get :about
    get :associate_membership
    get :symbols
    get :mission
    get :creed
  end

  namespace :house_duty_manager do
    root 'public#index'
    resources :house_duties
    resources :weekly_rosters
  end

  namespace :alpha do
    root 'public#index'
  end

  namespace :beta do
    root 'public#index'
  end

  namespace :gamma do
    root 'public#index'
    resources :users
    resources :offices
  end

  namespace :delta do
    root 'public#index'
  end

  namespace :user_profile do
    root 'user_profile#index'
  end

  resources :announcements do
    collection do
      get :tags
      get '/tags/*tags', to: 'announcements#tagged', as: 'tagged'
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/models/alpha.rb
module Alpha

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  acts_as_taggable
end

app/models/beta.rb
module Beta

end

app/models/delta.rb
module Delta

end

app/models/gamma.rb
module Gamma
end

app/models/house_duty_manager.rb
module HouseDutyManager
  def self.table_name_prefix
    'house_duty_manager_'
  end
end

app/models/office.rb
class Office < ActiveRecord::Base
  ALIASES = {
    pi:                 ["High Pi"],
    alpha:              ["High Alpha"],
    beta:               ["High Beta"],
    theta:              ["High Theta"],
    gamma:              ["High Gamma"],
    tau:                ["High Tau", "Assistant Tau"],
    iota:               ["High Iota"],
    rho:                ["High Rho"],
    kappa:              ["High Kappa"],
    delta:              ["High Delta", "Assistant Delta"],
    phi:                ["High Phi"],
    sigma:              ["High Sigma"],
    epsilon:            ["High Epsilon"],
    house_manager:      ["House Manager", "Assistant House Manager", "House Duty Manager"],
    ec:                 ["High Pi", "High Alpha", "High Beta", "High Tau", "First EC At-Large", "Second EC At-Large", "EC Alternate"],
    chapter_excellence: ["Chapter Excellence"],
    steward:            ["First Steward", "Second Steward"],
    house_duty_manager: ["House Duty Manager"],
    ifc:                ["Senior IFC Delegate", "Junior IFC Delegate"],
    sga:                ["SGA Representative"],
    co_jocks:           ["First Athletic Director", "Second Athletic Director"],
    greek_games:        ["First Greek Games Co-Chairman", "Second Greek Games Co-Chairman"],
    webmaster:          ["Webmaster"],
    historian:          ["Historian"]
  }

  has_many :terms
  belongs_to :advisor, class_name: "User"

  def current_officer
    terms.last.try(:officer)
  end
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :office
  belongs_to :officer, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :actives, -> { all }
  scope :in_house, -> { all }
end

app/controllers/alpha/public_controller.rb
class Alpha::PublicController < ApplicationController

  def index
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :require_login

  def index
    @announcements = Announcement.paginate(page: params[:page], per_page: 20).order(created_at: :desc)
  end

  def new
    @announcement = Announcement.new
  end

  def create
    announcement = Announcement.new(announcement_params)
    announcement.tag_list = params[:tags]
    if announcement.save
      flash[:success] = "Your announcement \"#{announcement.title}\" has been created!"
      redirect_to :announcements
    else
      redirect_to :back
    end
  end

  def show
    @announcement = Announcement.find(params[:id])
  end

  def tags
    respond_to do |f|
      f.json {
        render json: ActsAsTaggableOn::Tag.pluck(:name)
        .select {|n| n.include?(params[:query]) }
      }
    end
  end

  def tagged
    @tags = Set.new(params[:tags].split('/'))
    @announcements = Announcement.tagged_with(@tags.to_a).order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def announcement_params
    params.require(:announcement).permit(:title, :body) ## Rails 4 strong params usage
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_login
    unless current_user.present?
      flash[:danger] = "Please sign in to continue"
      redirect_to "/users/sign_in"
    end
  end

  def webmaster
    @webmaster ||= Office.find_by_title("Webmaster").current_officer
  end

  def restrict_to *groups
    permitted = (webmaster == current_user) || current_user_in_groups?(groups)

    unless permitted
      flash[:danger] = "You do not have sufficient permissions to view this content."
      redirect_to "/announcements"
    end
  end

  def current_user_in_groups?(groups)
    aliases, offices = groups.partition {|g| g.is_a? Symbol }
    permitted_office_names = offices + aliases.flat_map {|a| Office::ALIASES.fetch(a, []) }
    permitted_office_names.each do |name|
      office = Office.find_by_title(name)
      if office.current_officer == current_user || office.advisor == current_user
        return true
      end
    end

    false
  end

  def authenticate_inviter!
    restrict_to :gamma
  end
end

app/controllers/beta/public_controller.rb
class Beta::PublicController < ApplicationController

  def index
  end

end

app/controllers/delta/public_controller.rb
class Delta::PublicController < ApplicationController
  def index

  end
end

app/controllers/delta_controller.rb
class Delta::PublicController < ApplicationController
  def index

  end
end

app/controllers/gamma/public_controller.rb
class Gamma::PublicController < ApplicationController

  def index
  end

end

app/controllers/gamma/users_controller.rb
class Gamma::UsersController < GammaController
  def index
    @users = User.order(zeta_number: :desc).paginate(page: params[:page], per_page: params[:per_page])

    render layout: "wide"
  end

  def invite
  end
end

app/controllers/gamma_controller.rb
class GammaController < ApplicationController
  before_filter :access_policy

  def access_policy
    restrict_to :gamma
  end
end

app/controllers/house_duty_manager_controller.rb
class HouseDutyManagerController < ApplicationController
  before_filter { restrict_to :house_duty_manager }
end

app/controllers/learn_more_controller.rb
class LearnMoreController < ApplicationController
  def about
  end

  def associate_membership
  end

  def symbols
  end

  def mission
  end

  def creed
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_alias_for key
    case key.to_sym
    when :notice then :info
    else key
    end
  end
end

app/views/announcements/_announcement_list.html.haml
- @announcements.group_by {|a| a.created_at.to_date }.each do |(date, announcements)|
  %h2= date.to_formatted_s(:long)
  - announcements.each do |announcement|
    = link_to announcement_path(announcement) do
      %h3
        = announcement.title
        %small= announcement.created_at.to_time.strftime("%l:%M%p").strip
    %p= announcement.body.truncate(150)
    - tags = @tags.present? ? announcement.tag_list.reject {|t| @tags.include?(t) } : announcement.tag_list
    - tags.each do |tag|
      - if @tags.present?
        = link_to "#{@tags.to_a.join('/')}/#{tag}" do
          %span ##{tag}
      - else
        = link_to tagged_announcements_path(tag) do
          %span ##{tag}


.row
  = will_paginate @announcements, renderer: BootstrapPagination::Rails

app/views/announcements/index.html.haml
- content_for :title, "Announcements"

= link_to new_announcement_path do
  .btn.btn-default New Announcement

= render 'announcement_list'

app/views/announcements/new.html.haml
- content_for :title, "New Announcement"

= bootstrap_form_for @announcement do |f|
  = f.text_field :title
  = f.text_area :body
  .form-group
    = label_tag :tags
    %p.help-block Hint: Pressing <code>,</code> will end a tag.
    = text_field_tag :tags, @announcement.tag_list, "data-role" => "tagsinput"
    %script
      $(document).ready(function(){
      var tags = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.whitespace,
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      prefetch: {
      url: "/announcements/tags",
      filter: function(list) {
      return $.map(list, function(tag) {
      return { name: tag }; });
      }
      }
      });
      tags.initialize();

      $('input#tags').tagsinput({
      typeaheadjs: {
      name: 'tags',
      displayKey: 'name',
      valueKey: 'name',
      source: tags.ttAdapter()
      }
      });
      });


  = f.submit "Create", class: "btn btn-primary"

app/views/announcements/show.html.haml
- content_for :title, @announcement.title

%p= @announcement.body

- @announcement.tag_list.each do |tag|
  = link_to tagged_announcements_path(tag) do
    %span ##{tag}

app/views/announcements/tagged.html.haml
- content_for :title, "Announcements tagged with: #{@tags.to_a.map {|t| "##{t}" }.join(", ")}"

= render 'announcement_list'

app/views/beta/beta/index.html.haml
%h1 Welcome to the Beta Page