config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :learn_more do
    get :about
    get :associate_membership
    get :symbols
    get :mission
    get :creed
  end

  namespace :house_duty_manager do
    root 'public#index'
    resources :house_duties
    resources :weekly_rosters
  end

  namespace :alpha do
    root 'public#index'
  end

  namespace :beta do
    root 'public#index'
  end

  namespace :gamma do
    root 'public#index'
    resources :users
    resources :offices
  end

  namespace :delta do
    root 'public#index'
  end

  namespace :user_profile do
    root 'user_profile#index'
  end

  resources :announcements do
    collection do
      get :tags
      get '/tags/*tags', to: 'announcements#tagged', as: 'tagged'
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/models/house_duty_manager.rb
module HouseDutyManager
  def self.table_name_prefix
    'house_duty_manager_'
  end
end

app/models/house_duty_manager/assignment.rb
class HouseDutyManager::Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :allotment, class_name: "HouseDutyManager::WeeklyRosterAllotment", foreign_key: "allotment_id"
end

app/models/house_duty_manager/house_duty.rb
class HouseDutyManager::HouseDuty < ActiveRecord::Base
  has_many :allotments, class_name: "HouseDutyManager::WeeklyRosterAllotment"
end

app/models/house_duty_manager/weekly_roster.rb
class HouseDutyManager::WeeklyRoster < ActiveRecord::Base
  has_many :allotments, class_name: "HouseDutyManager::WeeklyRosterAllotment"
  accepts_nested_attributes_for :allotments
end

app/models/house_duty_manager/weekly_roster_allotment.rb
class HouseDutyManager::WeeklyRosterAllotment < ActiveRecord::Base
  belongs_to :weekly_roster, class_name: "HouseDutyManager::WeeklyRoster"
  belongs_to :house_duty, class_name: "HouseDutyManager::HouseDuty"

  has_many :assignments, class_name: "HouseDutyManager::Assignment", foreign_key: "allotment_id"

  validates :needed, acceptance: true

  attr_accessor :needed
end

app/controllers/house_duty_manager/house_duties_controller.rb
class HouseDutyManager::HouseDutiesController < HouseDutyManagerController
  def index
    @house_duties = HouseDutyManager::HouseDuty.all
  end

  def new
    @house_duty = HouseDutyManager::HouseDuty.new
  end

  def create
    house_duty = HouseDutyManager::HouseDuty.new(house_duty_params)

    if house_duty.save
      flash[:success] = "Created \"#{house_duty.name}\"!"
      redirect_to house_duty_manager_house_duties_path
    else
      redirect_to :back
    end
  end

  def edit
    @house_duty = HouseDutyManager::HouseDuty.find(params[:id])
  end

  def update
    house_duty = HouseDutyManager::HouseDuty.find(params[:house_duty_manager_house_duty][:id])
    house_duty.update_attributes(house_duty_params)
    if house_duty.save
      flash[:success] = "Updated \"#{house_duty.name}\"!"
      redirect_to house_duty_manager_house_duties_path
    else
      redirect_to :back
    end
  end

  private

  def house_duty_params
    params[:house_duty_manager_house_duty].permit(:name, :description, :default_count)
  end
end

app/controllers/house_duty_manager/public_controller.rb
class HouseDutyManager::PublicController < ApplicationController
  def index

  end
end

app/controllers/house_duty_manager/weekly_rosters_controller.rb
require 'house_duty_manager/generate_assignments'

class HouseDutyManager::WeeklyRostersController < HouseDutyManagerController
  def index
    @weekly_rosters = HouseDutyManager::WeeklyRoster.all
  end

  def show
    @weekly_roster = HouseDutyManager::WeeklyRoster.find(params[:id])
  end

  def new
    @weekly_roster = HouseDutyManager::WeeklyRoster.new
    @weekly_roster.allotments = HouseDutyManager::HouseDuty.all.map do |house_duty|
      HouseDutyManager::WeeklyRosterAllotment.new(weekly_roster: @weekly_roster, house_duty: house_duty, needed: true, count: house_duty.default_count)
    end
  end

  def create
    weekly_roster = HouseDutyManager::WeeklyRoster.new(weekly_roster_params)
    weekly_roster.allotments = weekly_roster.allotments.select {|a| a.needed == "1" }

    ActiveRecord::Base.transaction do
      if weekly_roster.save
        members = User.actives.in_house.to_a

        begin
          process = HouseDutyManager::GenerateAssignments.new(weekly_roster, members)
          process.run!
        rescue Exception => e
          raise e
          flash[:danger] = e.message
          redirect_to :back and return
        end

        flash[:success] = "Generated New Roster"
        redirect_to house_duty_manager_weekly_rosters_path
      else
        redirect_to :back
      end

    end
  end

  private

  def weekly_roster_params
    params.require(:house_duty_manager_weekly_roster).permit(allotments_attributes: [:house_duty_id, :needed, :count])
  end
end

app/controllers/house_duty_manager_controller.rb
class HouseDutyManagerController < ApplicationController
  before_filter { restrict_to :house_duty_manager }
end

app/views/house_duty_manager/house_duties/_form.html.haml
= bootstrap_form_for house_duty do |f|
  - unless house_duty.new_record?
    = f.hidden_field :id

  = f.text_field :name
  = f.text_area :description, rows: 4
  = f.number_field :default_count, min: 1

  - if house_duty.new_record?
    = f.submit "Create", class: "btn btn-success"
  - else
    = f.submit "Update", class: "btn btn-success"

app/views/house_duty_manager/house_duties/_subnavigation.html.haml
%ul.nav.nav-pills
  %li(role="presentation")
    = link_to "Weekly Roster", house_duty_manager_weekly_rosters_path
  %li.active(role="presentation")
    = link_to "House Duties", house_duty_manager_house_duties_path

app/views/house_duty_manager/house_duties/edit.html.haml
- content_for :title do
  Edit "#{@house_duty.name}"

= render partial: "house_duty_manager/house_duties/form", locals: { house_duty: @house_duty }

app/views/house_duty_manager/house_duties/index.html.haml
- content_for :title, "House Duties"

= link_to new_house_duty_manager_house_duty_path do
  .btn.btn-default New House Duty

%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th Default Count
  %tbody
    - @house_duties.each do |house_duty|
      %tr
        %td= link_to house_duty.name, edit_house_duty_manager_house_duty_path(house_duty)
        %td= house_duty.description
        %td= house_duty.default_count

app/views/house_duty_manager/house_duties/new.html.haml
- content_for :title, "New House Duty"

= render partial: "house_duty_manager/house_duties/form", locals: { house_duty: @house_duty }