config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :learn_more do
    get :about
    get :associate_membership
    get :symbols
    get :mission
    get :creed
  end

  namespace :house_duty_manager do
    root 'public#index'
    resources :house_duties
    resources :weekly_rosters
  end

  namespace :alpha do
    root 'public#index'
  end

  namespace :beta do
    root 'public#index'
  end

  namespace :gamma do
    root 'public#index'
    resources :users
    resources :offices
  end

  namespace :delta do
    root 'public#index'
  end

  namespace :user_profile do
    root 'user_profile#index'
  end

  resources :announcements do
    collection do
      get :tags
      get '/tags/*tags', to: 'announcements#tagged', as: 'tagged'
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/models/house_duty_manager.rb
module HouseDutyManager
  def self.table_name_prefix
    'house_duty_manager_'
  end
end

app/models/house_duty_manager/assignment.rb
class HouseDutyManager::Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :allotment, class_name: "HouseDutyManager::WeeklyRosterAllotment", foreign_key: "allotment_id"
end

app/models/house_duty_manager/house_duty.rb
class HouseDutyManager::HouseDuty < ActiveRecord::Base
  has_many :allotments, class_name: "HouseDutyManager::WeeklyRosterAllotment"
end

app/models/house_duty_manager/weekly_roster.rb
class HouseDutyManager::WeeklyRoster < ActiveRecord::Base
  has_many :allotments, class_name: "HouseDutyManager::WeeklyRosterAllotment"
  accepts_nested_attributes_for :allotments
end

app/models/house_duty_manager/weekly_roster_allotment.rb
class HouseDutyManager::WeeklyRosterAllotment < ActiveRecord::Base
  belongs_to :weekly_roster, class_name: "HouseDutyManager::WeeklyRoster"
  belongs_to :house_duty, class_name: "HouseDutyManager::HouseDuty"

  has_many :assignments, class_name: "HouseDutyManager::Assignment", foreign_key: "allotment_id"

  validates :needed, acceptance: true

  attr_accessor :needed
end

app/controllers/house_duty_manager/house_duties_controller.rb
class HouseDutyManager::HouseDutiesController < HouseDutyManagerController
  def index
    @house_duties = HouseDutyManager::HouseDuty.all
  end

  def new
    @house_duty = HouseDutyManager::HouseDuty.new
  end

  def create
    house_duty = HouseDutyManager::HouseDuty.new(house_duty_params)

    if house_duty.save
      flash[:success] = "Created \"#{house_duty.name}\"!"
      redirect_to house_duty_manager_house_duties_path
    else
      redirect_to :back
    end
  end

  def edit
    @house_duty = HouseDutyManager::HouseDuty.find(params[:id])
  end

  def update
    house_duty = HouseDutyManager::HouseDuty.find(params[:house_duty_manager_house_duty][:id])
    house_duty.update_attributes(house_duty_params)
    if house_duty.save
      flash[:success] = "Updated \"#{house_duty.name}\"!"
      redirect_to house_duty_manager_house_duties_path
    else
      redirect_to :back
    end
  end

  private

  def house_duty_params
    params[:house_duty_manager_house_duty].permit(:name, :description, :default_count)
  end
end

app/controllers/house_duty_manager/public_controller.rb
class HouseDutyManager::PublicController < ApplicationController
  def index

  end
end

app/controllers/house_duty_manager/weekly_rosters_controller.rb
require 'house_duty_manager/generate_assignments'

class HouseDutyManager::WeeklyRostersController < HouseDutyManagerController
  def index
    @weekly_rosters = HouseDutyManager::WeeklyRoster.all
  end

  def show
    @weekly_roster = HouseDutyManager::WeeklyRoster.find(params[:id])
  end

  def new
    @weekly_roster = HouseDutyManager::WeeklyRoster.new
    @weekly_roster.allotments = HouseDutyManager::HouseDuty.all.map do |house_duty|
      HouseDutyManager::WeeklyRosterAllotment.new(weekly_roster: @weekly_roster, house_duty: house_duty, needed: true, count: house_duty.default_count)
    end
  end

  def create
    weekly_roster = HouseDutyManager::WeeklyRoster.new(weekly_roster_params)
    weekly_roster.allotments = weekly_roster.allotments.select {|a| a.needed == "1" }

    ActiveRecord::Base.transaction do
      if weekly_roster.save
        members = User.actives.in_house.to_a

        begin
          process = HouseDutyManager::GenerateAssignments.new(weekly_roster, members)
          process.run!
        rescue Exception => e
          raise e
          flash[:danger] = e.message
          redirect_to :back and return
        end

        flash[:success] = "Generated New Roster"
        redirect_to house_duty_manager_weekly_rosters_path
      else
        redirect_to :back
      end

    end
  end

  private

  def weekly_roster_params
    params.require(:house_duty_manager_weekly_roster).permit(allotments_attributes: [:house_duty_id, :needed, :count])
  end
end

app/controllers/house_duty_manager_controller.rb
class HouseDutyManagerController < ApplicationController
  before_filter { restrict_to :house_duty_manager }
end

app/views/house_duty_manager/weekly_rosters/_subnavigation.html.haml
%ul.nav.nav-pills
  %li.active(role="presentation")
    = link_to "Weekly Roster", house_duty_manager_weekly_rosters_path
  %li(role="presentation")
    = link_to "House Duties", house_duty_manager_house_duties_path

app/views/house_duty_manager/weekly_rosters/index.html.haml
- content_for :title, "Weekly Rosters"

= link_to new_house_duty_manager_weekly_roster_path do
  .btn.btn-default Generate A Roster

%table.table
  %thead
    %tr
      %th Created At
  %tbody
    - @weekly_rosters.each do |weekly_roster|
      %tr
        %td= link_to weekly_roster.created_at, house_duty_manager_weekly_roster_path(weekly_roster)

app/views/house_duty_manager/weekly_rosters/new.html.haml
- content_for :title, "New Roster"

%p Uncheck all house duties that don't need to be done.

= form_for @weekly_roster do |f|
  %table.table
    %thead
      %tr
        %th
        %th House Duty
        %th Number of People Needed
    %tbody
      - f.object.allotments.each do |allotment|
        = f.fields_for :allotments, allotment do |ff|
          %tr
            = ff.hidden_field :house_duty_id, value: allotment.house_duty_id
            %td= ff.check_box :needed
            %td= allotment.house_duty.name
            %td= ff.number_field :count

  = f.submit "Generate Roster"

app/views/house_duty_manager/weekly_rosters/show.html.haml
- next_week = @weekly_roster.created_at.next_week
- content_for :title, "Weekly Roster for #{next_week.strftime("%B %d, %Y")}"

- @weekly_roster.allotments.each do |allotment|
  %h2
    = allotment.house_duty.name
    %small #{allotment.assignments.count} people assigned

  = link_to "Send Reminder for Sunday", "#"
  = link_to "Send Reminder for Wednesday", "#"

  %ul
    - allotment.assignments.each do |assignment|
      %li= assignment.user.name