config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :learn_more do
    get :about
    get :associate_membership
    get :symbols
    get :mission
    get :creed
  end

  namespace :house_duty_manager do
    root 'public#index'
    resources :house_duties
    resources :weekly_rosters
  end

  namespace :alpha do
    root 'public#index'
  end

  namespace :beta do
    root 'public#index'
  end

  namespace :gamma do
    root 'public#index'
    resources :users
    resources :offices
  end

  namespace :delta do
    root 'public#index'
  end

  namespace :user_profile do
    root 'user_profile#index'
  end

  resources :announcements do
    collection do
      get :tags
      get '/tags/*tags', to: 'announcements#tagged', as: 'tagged'
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/models/alpha.rb
module Alpha

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  acts_as_taggable
end

app/models/beta.rb
module Beta

end

app/models/delta.rb
module Delta

end

app/models/gamma.rb
module Gamma
end

app/models/house_duty_manager.rb
module HouseDutyManager
  def self.table_name_prefix
    'house_duty_manager_'
  end
end

app/models/office.rb
class Office < ActiveRecord::Base
  ALIASES = {
    pi:                 ["High Pi"],
    alpha:              ["High Alpha"],
    beta:               ["High Beta"],
    theta:              ["High Theta"],
    gamma:              ["High Gamma"],
    tau:                ["High Tau", "Assistant Tau"],
    iota:               ["High Iota"],
    rho:                ["High Rho"],
    kappa:              ["High Kappa"],
    delta:              ["High Delta", "Assistant Delta"],
    phi:                ["High Phi"],
    sigma:              ["High Sigma"],
    epsilon:            ["High Epsilon"],
    house_manager:      ["House Manager", "Assistant House Manager", "House Duty Manager"],
    ec:                 ["High Pi", "High Alpha", "High Beta", "High Tau", "First EC At-Large", "Second EC At-Large", "EC Alternate"],
    chapter_excellence: ["Chapter Excellence"],
    steward:            ["First Steward", "Second Steward"],
    house_duty_manager: ["House Duty Manager"],
    ifc:                ["Senior IFC Delegate", "Junior IFC Delegate"],
    sga:                ["SGA Representative"],
    co_jocks:           ["First Athletic Director", "Second Athletic Director"],
    greek_games:        ["First Greek Games Co-Chairman", "Second Greek Games Co-Chairman"],
    webmaster:          ["Webmaster"],
    historian:          ["Historian"]
  }

  has_many :terms
  belongs_to :advisor, class_name: "User"

  def current_officer
    terms.last.try(:officer)
  end
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :office
  belongs_to :officer, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :actives, -> { all }
  scope :in_house, -> { all }
end

app/controllers/alpha/public_controller.rb
class Alpha::PublicController < ApplicationController

  def index
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :require_login

  def index
    @announcements = Announcement.paginate(page: params[:page], per_page: 20).order(created_at: :desc)
  end

  def new
    @announcement = Announcement.new
  end

  def create
    announcement = Announcement.new(announcement_params)
    announcement.tag_list = params[:tags]
    if announcement.save
      flash[:success] = "Your announcement \"#{announcement.title}\" has been created!"
      redirect_to :announcements
    else
      redirect_to :back
    end
  end

  def show
    @announcement = Announcement.find(params[:id])
  end

  def tags
    respond_to do |f|
      f.json {
        render json: ActsAsTaggableOn::Tag.pluck(:name)
        .select {|n| n.include?(params[:query]) }
      }
    end
  end

  def tagged
    @tags = Set.new(params[:tags].split('/'))
    @announcements = Announcement.tagged_with(@tags.to_a).order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def announcement_params
    params.require(:announcement).permit(:title, :body) ## Rails 4 strong params usage
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_login
    unless current_user.present?
      flash[:danger] = "Please sign in to continue"
      redirect_to "/users/sign_in"
    end
  end

  def webmaster
    @webmaster ||= Office.find_by_title("Webmaster").current_officer
  end

  def restrict_to *groups
    permitted = (webmaster == current_user) || current_user_in_groups?(groups)

    unless permitted
      flash[:danger] = "You do not have sufficient permissions to view this content."
      redirect_to "/announcements"
    end
  end

  def current_user_in_groups?(groups)
    aliases, offices = groups.partition {|g| g.is_a? Symbol }
    permitted_office_names = offices + aliases.flat_map {|a| Office::ALIASES.fetch(a, []) }
    permitted_office_names.each do |name|
      office = Office.find_by_title(name)
      if office.current_officer == current_user || office.advisor == current_user
        return true
      end
    end

    false
  end

  def authenticate_inviter!
    restrict_to :gamma
  end
end

app/controllers/beta/public_controller.rb
class Beta::PublicController < ApplicationController

  def index
  end

end

app/controllers/delta/public_controller.rb
class Delta::PublicController < ApplicationController
  def index

  end
end

app/controllers/delta_controller.rb
class Delta::PublicController < ApplicationController
  def index

  end
end

app/controllers/gamma/users_controller.rb
class Gamma::UsersController < GammaController
  def index
    @users = User.order(zeta_number: :desc).paginate(page: params[:page], per_page: params[:per_page])

    render layout: "wide"
  end

  def invite
  end
end

app/controllers/gamma_controller.rb
class GammaController < ApplicationController
  before_filter :access_policy

  def access_policy
    restrict_to :gamma
  end
end

app/controllers/house_duty_manager_controller.rb
class HouseDutyManagerController < ApplicationController
  before_filter { restrict_to :house_duty_manager }
end

app/controllers/learn_more_controller.rb
class LearnMoreController < ApplicationController
  def about
  end

  def associate_membership
  end

  def symbols
  end

  def mission
  end

  def creed
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_alias_for key
    case key.to_sym
    when :notice then :info
    else key
    end
  end
end

app/views/learn_more/about.html.haml
- content_for :title, "About Lambda Chi Alpha"

%blockquote
  &ldquo;Committed to the ideas of fraternity, I know that the men of Lambda Chi
  Alpha will give their best efforts to the struggle to bring tranquility and
  peace through world understanding and the sharing of the fruits of freedom...
  we who know the meaning of brotherhood must practice it.&rdquo; - Harry S. Truman

%section
  %h2 Associate Membership Program
  %p
    Lambda Chi Alpha did away with the archaic pledge system and instituted the
    Associate Member program. The Associate Membership program is an orientation
    to fraternity life within Lambda Chi Alpha.
  = link_to "Click Here For More Info", learn_more_associate_membership_path

%section
  %h2 Symbols of Lambda Chi Alpha
  %p
    All college fraternities have special symbols, but few have created their
    design with such faithful adherence to the laws of the ancient art of heraldry
    as has Lambda Chi Alpha.
  = link_to "Click Here For More Info", learn_more_symbols_path

%section
  %h2 Lambda Chi Alpha International
  %p
    Lambda Chi Alpha was founded by Warren A. Cole, while a student at Boston
    University, on November 2, 1909; with the expressed objective purpose of
    bringing about the association together of college students of good moral
    character in the various collegiate institutions within the United States and
    Canada; to foster a high Christian standard of life and ideals, to promote
    honorable friendship, to cultivate intellectual excellence, to secure for
    members the greatest advantages in college life, to establish brotherly love,
    mutual aid, close personal connection between alumni, undergraduates and
    college, and to bind them together for mutual pleasure and interest in college
    as well as after life by testing each with courage, self-control, obedience,
    democracy and courtesy toward all with whom the may come in contact.
  = link_to "Click Here For More Info", "http://lambdachi.org"

app/views/learn_more/associate_membership.html.haml
- content_for :title, "Don't Pledge Us, Join Us!"

%p
  Lambda Chi Alpha did away with the archaic pledge system and instituted the
  Associate Member program. Lambda Chi wanted to get away from the "pledge
  class." You do not join the Fraternity to just be with the other Associate
  Members. That is why we fully integrated the Associate Members with the
  Brothers. Brotherhood is learned through personal experience, one on one. The
  Associate Membership program is an orientation to fraternity life within
  Lambda Chi Alpha.

%p
  The mission of the New Member Orientation Program is to use the most
  productive brothers to generate new members who will be both better brothers
  and men through awareness of their responsibilities to the Fraternity and
  academic institution. The orientation program strives to expose the new
  members to a variety of chapter activities in order to fully develop a
  commitment to the Fraternity. To continue the education program beyond
  orientation, Fraternity Education continues to enhance the learning process by
  educating the member on the chapter, community, and world topics throughout
  one's college years.

%p
  There is a profound difference between an associate member and a pledge
  member. The associate program does not have the emotional stress of a pledge
  program. The associate program builds house unity as opposed to "class" unity
  as associate members are not kept apart from the initiated members.

%ul
  %li Associates are brought in as equals.
  %li Associates have the same rights as active members.
  %li Associates are never asked to do anything they don't want to do.
  %li Associates can wear our house letters.
  %li Associates can hold offices in the house.

%p
  Our coat of arms bears a Latin inscription -- "Vir Quisque Vir," or "Every Man,
  a Man." This motto is applied everyday within our house. Everyone in the house
  is recognized to be worthy of respect. An associate member has the right to
  confront any brother that he feels is not living up to his part as a brother.
  Another characteristic of an associate is the sharing of kitchen and other
  household duties with active members through a weekly rotation. The only
  difference between an associate and an active is the understanding and
  knowledge of our rituals. There is absolutely no hazing!

%p
  Associate With The Best!
  %strong
    Lambda Chi Alpha

app/views/learn_more/creed.html.haml
- content_for :title, "The Creed of Lambda Chi Alpha"

.row
  .col-md-8
    %section
      %p
        We believe in Lambda Chi Alpha, and its traditions, principles, and
        ideals. The crescent is our symbol, pure, high and ever growing, and the cross
        is our guide: denoting service, sacrifice, and even suffering and humiliation
        before the world, bravely endured if need be, in following that ideal.
      %p
        May we have faith in Lambda Chi Alpha and passion for its welfare. May we
        have hope for the future of Lambda Chi Alpha and strength to fight for its
        teachings. May we have pure hearts that we may approach the ideal of perfect
        brotherly love.

  .col-md-4
    = image_tag "the-lamp.png", class: "img-responsive"

app/views/learn_more/mission.html.haml
- content_for :title, "The Vision and Mission of Lambda Chi Alpha"

.row
  .col-md-8
    %section
      %h2 Vision
      %p
        The vision of Lambda Chi Alpha Fraternity is to prepare and encourage
        collegiate men of good character, high ethics, and noble ideals to contribute
        positively to the world in which they live.

    %section
      %h2 Mission
      %p
        The mission of Lambda Chi Alpha is to offer the best fraternal
        experience, focusing on personal character development through leadership,
        scholarship, community service, and positive social experiences.
      %p
        The mission of Lambda Chi Alpha Fraternity staff is to provide the
        highest ethical and professional service to our undergraduate and alumni
        members in a spirit of unity and enthusiasm through the:

        %ul
          %li Development of quality programs, publications, and services
          %li Responsible use of Fraternity resources
          %li Commitment to excellence in chapter standards
          %li Advancement and promotion of the ideals and principles of the Fraternity as a complement to the educational experience

  .col-md-4
    = image_tag "coat-of-arms-2.jpg", class: "img-responsive"

app/views/learn_more/symbols.html.haml
- content_for :title, "Symbols of Lambda Chi Alpha"

.row
  .col-md-8
    %section
      %h2 Coat of Arms
      %p
        Coat of arms originated as family emblems, then cities, societies, and
        institutions adopted them. All college fraternities have them, but few have
        created their design with such faithful adherence to the laws of the ancient
        art of heraldry as has Lambda Chi Alpha.

      %p
        Designed by Jack Mason of Epsilon Zeta (University of Pennsylvania), our coat
        of arms displays our three open mottos, translated from top to bottom,
        &ldquo;Crescent in the Cross,&rdquo; &ldquo;Naught Without Labor,&rdquo;
        and &ldquo;Every Man a Man.&rdquo; Present are the crucicrescent, the lamp of
        learning, the clasped hands of brotherhood, and other symbols, as well as the
        inescutcheon signifying our merger with Theta Kappa Nu (the white rose is our
        fraternity flower) and the badge of membership below. In the medieval rules of
        heraldry it would be described as such:

      %p
        %strong Escutcheon:
        quarterly 1, vert, a lighten Greek lamp or; 2, or, an open book proper, bearing
        on its face the letters Chi, Omicron, Alpha Zeta; 3, able, a balance, or; 4,
        vert, a pair of clasped hands argent, between three mullets in chevron or;
        over all an inescutcheon argent, lion rampant holding a white rose slipped
        proper.

      %p
        %strong Behind the escutcheon
        a pair of swords in saltire, points downward, argent,
        pommels, and hilts or. Mantling vert, lined, or.

      %p
        %strong Encircling the escutcheon
        a riband purpire, edged argent, bearing the Greek motto Chalepa ta Kala
        surronded by an olive wreath which bears pendant the badge of the
        brotherhood.

      %p
        %strong Below the escutcheon
        a scroll with the Latin motto Vir Quisque Vir.

      %p
        %strong Crest:
        issuant from a crown celestial or, ensigning a gentlemen's helmet proper, a
        crucicrescent rayonne or, Latin motto Per Crucam Crescens, on scroll.

      %p
        %em
          From Baird's Manual of American College Fraternities, 19th Edition,
          (1977), p300.

  .col-md-4
    = image_tag "coat-of-arms.jpg", class: "img-responsive"

.row
  .col-md-8
    %section
      %h2 The Badge

      %p
        The badge is a pearl-set crescent with horns turned toward the left,
        enclosing a monogram of the Greek letters Lambda, Chi, and Alpha. The center
        of the crescent bears the Greek letters Delta and Pi in gold on black enamel.
        A variety of jewels may be selected for the Lambda.

      %p
        The badge of Lambda Chi Alpha is among the most meaningful in the
        fraternal world. Each stone, letter, and line, and each circle of the crescent
        has a special meaning.

      %p
        Our badge is made with the lambda being struck separately from a single
        piece comprising the chi, alpha, and crescent. The background for the letters
        delta and pi is enameled, and the lambda is joined to the remainder of the
        badge (always yellow, white, or green gold) before the eight crescent pearls
        and (optional) stones in the lambda are set.

      %p
        The badge is properly worn over the heart, preferably with a badge
        guard bearing a monogram of the member’s zeta designation, and only by
        initiated members, their wives, and their fiancees (special exceptions may be
        made for some housemothers).
  .col-md-4
    = image_tag "the-badge.png", class: "img-responsive"

.row
  .col-md-8
    %section
      %h2 Associate Member Pin
      %p
        The associate member pin has a most interesting history because it
        embodies the official badge of Theta Kappa Nu as well as the original new
        member pin of Lambda Chi Alpha. The original Lambda Chi Alpha pin was a gothic
        arch, and with the union, this was superimposed upon the triangles composing
        the official badge of Theta Kappa Nu.
  .col-md-4
    = image_tag "the-pin.png", class: "img-responsive"

.row
  .col-md-8
    %section
      %h2 The Seal
      %p
        The seal is used to identify official General Fraternity documents and
        publications. It should not be used for decoration, as an ornament for
        jewelry, stationery, etc., unless it is to be used as the official stationery
        for the General Fraternity. It is now properly used on charters, membership
        certificates, and authorized publications of the General Fraternities.

      %p
        The design consists of the cross and crescent upon which is superimposed a
        shield bearing the letters of the Fraternity, above all of which appears a
        gothic circle bearing in Greek the inscription, &ldquo;Seal of the Brotherhood of
        Lambda Chi Alpha.&rdquo;
  .col-md-4
    = image_tag "the-seal.png", class: "img-responsive"

.row
  .col-md-8
    %section
      %h2 The Flag
      %p
        The Lambda Chi Alpha flag may be flown on appropriate occasions or
        placed on a wall. Chapters may place their Zeta letters in the upper right
        corner to identify their flags.
  .col-md-4
    = image_tag "the-flag.png", class: "img-responsive"

.row
  .col-md-12
    %section
      %h2 The Flower
      %p
        The Fraternity flower is the white rose.

.row
  .col-md-12
    %section
      %h2 The Colors
      %p
        The Fraternity colors are purple, green, and gold.

app/views/welcome/index.html.haml
- content_for :title do
  Home

.row
  %article
    .col-md-8.col-md-offset-2
      %section
        %h2 Lambda Chi Alpha International Fraternity
        %p
          Lambda Chi Alpha International Fraternity is one of the largest
          men&rsquo;s general fraternities in North America. Founded in 1909 at
          Boston University, it has more than 227,000 initiated members and has
          held subsidiaries (called chapters) at more than 300 universities.
          Designed to prepare its members to be leaders for the world in which
          they will live, Lambda Chi Alpha has a mission to inspire the highest
          level of character, values, scholarship, and service in each of its
          members. It was the first fraternity to eliminate pledging and
          remains a leader in the fight against hazing, alcohol abuse, and
          other challenges facing today's college student. Lambda Chi Alpha
          serves to complement higher education by providing opportunities for
          academic achievement, leadership development, and lifelong friendships.

      %section
        %h2 Don't Pledge Us, Join Us!

        %p
          Lambda Chi Alpha did away with the archaic pledge system and
          instituted the Associate Member program. Lambda Chi wanted to get away from
          the "pledge class." You do not join the Fraternity to just be with the other
          Associate Members. That is why we fully integrated the Associate Members with
          the Brothers. Brotherhood is learned through personal experience, one on one.
          The Associate Membership program is an orientation to fraternity life within
          Lambda Chi Alpha.

      %section
        %h2 Vision

        %p
          The vision of Lambda Chi Alpha Fraternity is to prepare and encourage
          collegiate men of good character, high ethics, and noble ideals to contribute
          positively to the world in which they live.

      %section
        %h2 Mission

        %p
          The mission of Lambda Chi Alpha is to offer the best fraternal experience,
          focusing on personal character development through leadership, scholarship,
          community service, and positive social experiences. The mission of Lambda Chi
          Alpha Fraternity staff is to provide the highest ethical and professional
          service to our undergraduate and alumni members in a spirit of unity and
          enthusiasm through the: Development of quality programs, publications, and
          services; Responsible use of Fraternity resources; Commitment to excellence in
          chapter standards; Advancement and promotion of the ideals and principles of
          the Fraternity as a complement to the educational experience.

      %section
        %h2 Contact Us
        %p Feel free to contact us at #{ mail_to("sanderib@rose-hulman.edu") }.